# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_FPC)		+= fpc/
obj-$(CONFIG_FINGERPRINT_GOODIX_FOD)	+= goodix/
